security.jwt.secret=VGhpcy1pcy1hLXNpbXBsZS1CYXNlNjQtU0VDUkVULWF0LWxlYXN0LTI1Ni1iaXRzIQ==
security.jwt.access-exp-min=60
server.port=8081
confirmation.token.expiration-hours=24

# --- H2 (OFF) ---
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:file:./data/dev-db;AUTO_SERVER=TRUE
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true

#--- MySQL (ON) ---
# useSSL=false ? ?? ?????????? ?????????? (?????????? ?? ?????????).
# ? ?????????? ???????? TLS: useSSL=true + ?????????? ???????????/CA.
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/boxingclub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:appuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:apppass}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}

spring.web.resources.add-mappings=false
spring.jackson.serialization.write-dates-as-timestamps=false

spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587
spring.mail.username=7d16d1061269e1
spring.mail.password=0d1425214ba181
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=sandbox.smtp.mailtrap.io

server.error.include-message=always
logging.level.org.apache.coyote=DEBUG
logging.level.org.springframework.web=INFO
logging.level.com.fasterxml.jackson.databind=INFO
logging.level.org.springframework.security=DEBUG
logging.level.de.oleinikova.boxingclub.backend.security=DEBUG
