spring.application.name=boxingclub-backend

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev,mailtrap}
security.jwt.enabled=true
security.jwt.secret=${JWT_SECRET}
security.jwt.access-exp-min=${JWT_ACCESS_EXP_MIN:60}

app.backend-url=${BACKEND_URL:http://localhost:8081}
app.frontend-url=${FRONTEND_URL:http://localhost:5173}

security.email-confirmation.expiration-minutes=${CONFIRMATION_EXPIRATION_MINUTES:90}
security.password-reset.expiration-seconds=${PASSWORD_RESET_EXPIRATION_SECONDS:3600}
management.endpoints.web.exposure.include=health


ai.groq.key=${GROQ_API_KEY}
ai.groq.url=https://api.groq.com/openai/v1/chat/completions
ai.groq.model=openai/gpt-oss-120b

telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.enabled=${TELEGRAM_BOT_ENABLED:false}
telegram.bot.link-token-expiration-minutes=${TELEGRAM_LINK_TOKEN_EXPIRATION_MINUTES:10}

app.demo-data.enabled=${APP_DEMO_DATA_ENABLED:false}